[package]
name = "clpeek"
description = "Guess the color displayed in hex format"
version = "0.1.2"
edition = "2021"
license = "MIT"
authors = ["CRCR"]

[dependencies]
colored = "2.2.0"
eyre = "0.6.12"
rand = "0.8.5"
